# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

env:
  BOOST_VER: 1.89.0


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-boost:
    runs-on: windows-latest
    steps:
    
    - name: Build Boost 
      run: |
          cd C:
          iwr -outf boost-${{env.BOOST_VER}}.zip https://github.com/boostorg/boost/archive/refs/tags/boost-${{env.BOOST_VER}}.zip
          unzip boost-${{env.BOOST_VER}}.zip
          cd boost-${{env.BOOST_VER}}
          mkdir build
          bootstrap
          b2 --help
          b2 --build-dir=build toolset=gcc --build-type=complete
          
