# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BOOST_VER: 1.92.0

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc]
        cpp_compiler: [g++]

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      if: runner.os == 'Linux'
      id: strings
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Set reusable strings
      if: runner.os == 'Windows'
      shell: bash
      id: strings
      run: echo "build-output-dir=${{ github.workspace }}\build" >> "$GITHUB_OUTPUT"

    - name: Restore Boost from Cache
      id: restore-cache-Boost
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.strings.outputs.build-output-dir }}/boost-${{env.BOOST_VER}}
        key: ${{ runner.os }}-Boost-${{ env.BOOST_VER }}

    - name: Build Boost
      shell: bash
      if: steps.restore-cache-Boost.outputs.cache-hit != 'true'
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        wget https://github.com/boostorg/boost/releases/download/boost-${{env.BOOST_VER}}/boost-${{env.BOOST_VER}}-cmake.tar.xz
        tar -xJf boost-${{env.BOOST_VER}}-cmake.tar.xz
        cd boost-${{env.BOOST_VER}}
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBOOST_RUNTIME_LINK=static -DBUILD_SHARED_LIBS=OFF -DBOOST_INCLUDE_LIBRARIES="program_options;nowide;predef;tokenizer"
        cmake --build build

    - name: Save Boost to Cache
      if: steps.restore-cache-Boost.outputs.cache-hit != 'true'
      id: save-cache-Boost
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.strings.outputs.build-output-dir }}/boost-${{env.BOOST_VER}}
        key: ${{ runner.os }}-Boost-${{ env.BOOST_VER }}

    - name: Install Boost
      shell: bash
      working-directory: ${{ steps.strings.outputs.build-output-dir }}/boost-${{env.BOOST_VER}}
      run: sudo cmake --build build --target install

    - name: ubuntu install poppler
      if: runner.os == 'Linux'
      run: sudo apt install -y poppler-utils

    - name: windows install poppler
      if: runner.os == 'Windows'
      shell: bash
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        wget https://github.com/oschwartz10612/poppler-windows/releases/download/v26.02.0-0/Release-26.02.0-0.zip
        unzip -qq Release-26.02.0-0.zip
        echo "${{ steps.strings.outputs.build-output-dir }}/poppler-26.02.0/Library/bin" >> $GITHUB_PATH

    - name: Configure CMake
      working-directory: ${{ github.workspace }}
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      working-directory: ${{ github.workspace }}
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }} --verbose

    - name: Upload Linux artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4.6.2
      with:
        name: dompdfui_linux_x86_64
        path: ${{ steps.strings.outputs.build-output-dir }}/dompdfui
        compression-level: 0

    - name: Upload Windows Artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: dompdfui_windows_x86_64
        path: ${{ steps.strings.outputs.build-output-dir }}\dompdfui.exe
        compression-level: 0
