name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BOOST_VER: 1.92.0

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:

      - name: Install Dependencies
        run: sudo apt-get install -y poppler-utils
          
      - name: Restore Boost from Cache
        id: restore-cache-Boost
        uses: actions/cache/restore@v4
        with:
          path: ~/boost-${{env.BOOST_VER}}
          key: ${{ runner.os }}-Boost-${{ env.BOOST_VER }}

      - name: Build Boost
        if: steps.restore-cache-Boost.outputs.cache-hit != 'true'
        run: |
          cd ~
          wget https://github.com/boostorg/boost/releases/download/boost-${{env.BOOST_VER}}/boost-${{env.BOOST_VER}}-cmake.tar.xz
          tar -xJf boost-${{env.BOOST_VER}}-cmake.tar.xz
          cd boost-${{env.BOOST_VER}}
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBOOST_RUNTIME_LINK=static -DBUILD_SHARED_LIBS=OFF -DBOOST_INCLUDE_LIBRARIES="program_options;nowide;predef;tokenizer"
          cmake --build build

      - name: Save Boost to Cache
        if: steps.restore-cache-Boost.outputs.cache-hit != 'true'
        id: save-cache-Boost
        uses: actions/cache/save@v4
        with:
          path: ~/boost-${{env.BOOST_VER}}
          key: ${{ runner.os }}-Boost-${{ env.BOOST_VER }}

      - name: Install Boost
        run: |
          cd ~/boost-${{env.BOOST_VER}}
          sudo cmake --build build --target install

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build project
        id: build-project
        run: |
          cd $GITHUB_WORKSPACE
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Test project
        id: test-project
        run: |
          cd $GITHUB_WORKSPACE/build
          ctest --verbose 

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dompdfui_linux_x86_64
          path: build/dompdfui
          compression-level: 0


  build-windows:
    runs-on: windows-latest
    steps:

      - name: Install Dependencies
        run: |
          cd C:
          iwr -outf Release-26.02.0-0.zip https://github.com/oschwartz10612/poppler-windows/releases/download/v26.02.0-0/Release-26.02.0-0.zip
          unzip Release-26.02.0-0.zip
          echo "C:\poppler-26.02.0\Library\bin" >> $GITHUB_PATH
        
      - name: Restore Boost from Cache
        id: restore-cache-Boost
        uses: actions/cache/restore@v4
        with:
          path: C:\boost-${{env.BOOST_VER}}
          key: ${{ runner.os }}-Boost-${{ env.BOOST_VER }}

      - name: Build Boost
        if: steps.restore-cache-Boost.outputs.cache-hit != 'true'
        run: |
          cd C:
          iwr -outf boost-${{env.BOOST_VER}}.zip https://github.com/boostorg/boost/releases/download/boost-${{env.BOOST_VER}}/boost-${{env.BOOST_VER}}-cmake.zip
          unzip boost-${{env.BOOST_VER}}.zip
          cd boost-${{env.BOOST_VER}}
          cmake -G "MinGW Makefiles" -S . -B build -DCMAKE_BUILD_TYPE=Release -DBOOST_RUNTIME_LINK=static -DBUILD_SHARED_LIBS=OFF -DBOOST_INCLUDE_LIBRARIES="program_options;nowide;predef;tokenizer"
          cmake --build build

      - name: Save Boost to Cache
        if: steps.restore-cache-Boost.outputs.cache-hit != 'true'
        id: save-cache-Boost
        uses: actions/cache/save@v4
        with:
          path: C:\boost-${{env.BOOST_VER}}
          key: ${{ runner.os }}-Boost-${{ env.BOOST_VER }}

      - name: Install Boost
        run: |
          cd C:\boost-${{env.BOOST_VER}}
          cmake --build build --target install

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build project
        id: build-project
        run: |
          cmake -G "MinGW Makefiles" -S . -B build -DCMAKE_BUILD_TYPE=Release -DBoost_DIR="C:/Boost/lib/cmake/Boost-${{ env.BOOST_VER }}" -DCMAKE_TLS_VERIFY=OFF
          cmake --build build

      - name: Test project
        id: test-project
        working-directory: $GITHUB_WORKSPACE\build
        run: ctest -V

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dompdfui_windows_x86_64
          path: build\dompdfui.exe
          compression-level: 0

